version: '3'
services:
  app:
    build: ./src/Replenishment.API
    environment:
      - SERVER_PASS_PHRASE=qwerty12345
      - SERVER_KEY_PAIR_FILE=my-keypair.json
    ports: 
      - "8080:8080"
    networks:
      - app-network
  
  web:
    build: ./src/web
    ports: 
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge